const express = require("express");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 3000;

//serve static files form project root
app.use(express.static(path.join(__dirname)));

//basic health endpoint
app.get("/health", (_req, res) => {
  res.status(200).send("OK");
});

//Root -> index.html
app.get("/", (_req, res) => {
  res.sendFile(path.join(__dirname, "index.html"));
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// code generated by copiolt i hand typed this so i can actualy remember what the heck is going on lol
